import {
  MdShoppingCart,
  MdLocalPharmacy,
  MdRestaurant,
  MdPhoneIphone,
  MdCheckroom,
} from "react-icons/md";

export const storesData = [
  {
    id: 1,
    name: "QuickMart Express",
    category: "grocery",
    rating: 4.5,
    deliveryTime: "10-15 min",
    icon: MdShoppingCart,
    iconColor: "#10b981",
    distance: "0.5 km",
    tags: ["Groceries", "Daily Essentials"],
    items: ["Milk", "Bread", "Eggs", "Butter", "Rice", "Atta", "Oil", "Sugar", "Soap", "Shampoo", "Fruits", "Vegetables"],
    offer: "Up to 40% OFF",
    image: "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=400&q=80",
    location: "Law Gate Road, Near LPU",
    reviewCount: "17K+"
  },
  {
    id: 2,
    name: "MediCare Plus",
    category: "pharmacy",
    rating: 4.8,
    deliveryTime: "20-25 min",
    icon: MdLocalPharmacy,
    iconColor: "#ef4444",
    distance: "1.2 km",
    tags: ["Medicines", "Health Products"],
    items: ["Paracetamol", "Insulin", "Masks", "Sanitizer", "Band-aid", "Vitamins", "Baby Care", "Protein Powder"],
    offer: "Flat 20% OFF",
    image: "https://images.unsplash.com/photo-1586015555751-63bb77f4322a?w=400&q=80",
    location: "Highway Plaza Market, Near LPU",
    reviewCount: "5K+"
  },
  {
    id: 3,
    name: "FoodHub Kitchen",
    category: "food",
    rating: 4.3,
    deliveryTime: "30-35 min",
    icon: MdRestaurant,
    iconColor: "#f59e0b",
    distance: "2.0 km",
    tags: ["Fast Food", "North Indian"],
    items: ["Pizza", "Burger", "Pasta", "Paneer Tikka", "Dal Makhani", "Roti", "Biryani", "Coca Cola", "Dessert"],
    offer: "50% OFF up to ₹100",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&q=80",
    location: "Law Gate Market, Near LPU Girls Hostel",
    reviewCount: "12K+"
  },
  {
    id: 4,
    name: "Tech World Store",
    category: "electronics",
    rating: 4.6,
    deliveryTime: "40-45 min",
    icon: MdPhoneIphone,
    iconColor: "#3b82f6",
    distance: "3.5 km",
    tags: ["Electronics", "Gadgets"],
    items: ["iPhone", "Samsung", "Headphones", "Charger", "Laptop", "Mouse", "Keyboard", "Power Bank", "Smart Watch"],
    offer: "Up to 30% OFF",
    image: "https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=400&q=80",
    location: "LPU Campus, Block 15-A",
    reviewCount: "8K+"
  },
  {
    id: 5,
    name: "Fashion Hub",
    category: "fashion",
    rating: 4.4,
    deliveryTime: "45-50 min",
    icon: MdCheckroom,
    iconColor: "#8b5cf6",
    distance: "2.8 km",
    tags: ["Clothing", "Accessories"],
    items: ["T-shirt", "Jeans", "Jacket", "Shirt", "Dress", "Shoes", "Socks", "Belt", "Wallet", "Sunglasses"],
    offer: "Buy 2 Get 1 Free",
    image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=400&q=80",
    location: "Highway Plaza Mall, Law Gate Road",
    reviewCount: "3K+"
  },
];
