import {
  MdShoppingCart,
  MdLocalPharmacy,
  MdRestaurant,
  MdPhoneIphone,
  MdCheckroom,
} from "react-icons/md";

export const storesData = [
  {
    id: 1,
    name: "QuickMart Express",
    category: "grocery",
    rating: 4.5,
    deliveryTime: "10-15 min",
    icon: MdShoppingCart,
    iconColor: "#10b981",
    distance: "0.5 km",
    tags: ["Groceries", "Daily Essentials"],
    offer: "Up to 40% OFF",
  },
  {
    id: 2,
    name: "MediCare Plus",
    category: "pharmacy",
    rating: 4.8,
    deliveryTime: "20-25 min",
    icon: MdLocalPharmacy,
    iconColor: "#ef4444",
    distance: "1.2 km",
    tags: ["Medicines", "Health Products"],
    offer: "Flat 20% OFF",
  },
  {
    id: 3,
    name: "FoodHub Kitchen",
    category: "food",
    rating: 4.3,
    deliveryTime: "30-35 min",
    icon: MdRestaurant,
    iconColor: "#f59e0b",
    distance: "2.0 km",
    tags: ["Fast Food", "North Indian"],
    offer: "50% OFF up to ₹100",
  },
  {
    id: 4,
    name: "Tech World Store",
    category: "electronics",
    rating: 4.6,
    deliveryTime: "40-45 min",
    icon: MdPhoneIphone,
    iconColor: "#3b82f6",
    distance: "3.5 km",
    tags: ["Electronics", "Gadgets"],
    offer: "Up to 30% OFF",
  },
  {
    id: 5,
    name: "Fashion Hub",
    category: "fashion",
    rating: 4.4,
    deliveryTime: "45-50 min",
    icon: MdCheckroom,
    iconColor: "#8b5cf6",
    distance: "2.8 km",
    tags: ["Clothing", "Accessories"],
    offer: "Buy 2 Get 1 Free",
  },
];
